package map;

import set_get.set_get;

public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        boton_partida = new javax.swing.JButton();
        boton_destino = new javax.swing.JButton();
        boton_informacion = new javax.swing.JButton();
        puntos_salida = new javax.swing.JComboBox<>();
        puntos_destino = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel_ruta = new javax.swing.JTextPane();
        info_lugares = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        panel_informacion1 = new javax.swing.JTextPane();
        boton_ruta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapa");
        setBackground(new java.awt.Color(150, 152, 154));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("map.png"))); // NOI18N
        jButton4.setText("jButton4");

        boton_partida.setText("Seleccionar");
        boton_partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_partidaActionPerformed(evt);
            }
        });

        boton_destino.setText("Seleccionar ");
        boton_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_destinoActionPerformed(evt);
            }
        });

        boton_informacion.setText("Seleccionar");
        boton_informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_informacionActionPerformed(evt);
            }
        });

        puntos_salida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alajuela", "Alajuelita", "Belen", "Coronado", "Curridabat", "Desamparados", "Escazu", "Heredia", "Moravia", "Pavas", "Pozos", "Sabana", "San Pedro", "Santa Ana", "Zapote" }));

        puntos_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alajuela", "Alajuelita", "Belen", "Coronado", "Curridabat", "Desamparados", "Escazu", "Heredia", "Moravia", "Pavas", "Pozos", "Sabana", "San Pedro", "Santa Ana", "Zapote" }));

        jScrollPane3.setViewportView(panel_ruta);

        info_lugares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alajuela", "Alajuelita", "Belen", "Coronado", "Curridabat", "Desamparados", "Escazu", "Heredia", "Moravia", "Pavas", "Pozos", "Sabana", "San Pedro", "Santa Ana", "Zapote" }));

        jScrollPane4.setViewportView(panel_informacion1);

        boton_ruta.setText("Obtener");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puntos_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(boton_partida, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puntos_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addGap(106, 106, 106)
                        .addComponent(boton_ruta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info_lugares, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(2158, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1350, 1350, 1350)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(2290, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_destino)
                            .addComponent(boton_partida))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(puntos_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puntos_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(boton_informacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(info_lugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(boton_ruta)))))
                .addContainerGap(1166, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(482, 482, 482)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1241, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents





    private void boton_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_destinoActionPerformed
        // TODO add your handling code here:

        String destino = (String) puntos_destino.getSelectedItem();
        System.out.println(destino);
        set_get.getInstance().setPuntos_destino(destino);


    }//GEN-LAST:event_boton_destinoActionPerformed

    private void boton_partidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_partidaActionPerformed
        // TODO add your handling code here:

        String salida = (String) puntos_salida.getSelectedItem();
        System.out.println(salida);
        set_get.getInstance().setPuntos_salida(salida);



    }//GEN-LAST:event_boton_partidaActionPerformed

    private void boton_informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_informacionActionPerformed
        // TODO add your handling code here:
        
        //Obtener informacion de un Jcombobox
        String info_Lugar = (String) info_lugares.getSelectedItem();
        System.out.println(info_Lugar);
        set_get.getInstance().setInfo_lugares(info_Lugar);

    }//GEN-LAST:event_boton_informacionActionPerformed









    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_destino;
    private javax.swing.JButton boton_informacion;
    private javax.swing.JButton boton_partida;
    private javax.swing.JButton boton_ruta;
    private javax.swing.JComboBox<String> info_lugares;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane panel_informacion1;
    private javax.swing.JTextPane panel_ruta;
    private javax.swing.JComboBox<String> puntos_destino;
    private javax.swing.JComboBox<String> puntos_salida;
    // End of variables declaration//GEN-END:variables
}
