package map;

import set_get.set_get;

public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        boton_partida = new javax.swing.JButton();
        boton_destino = new javax.swing.JButton();
        boton_informacion = new javax.swing.JButton();
        puntos_salida = new javax.swing.JComboBox<>();
        puntos_destino = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel_ruta = new javax.swing.JTextPane();
        info_lugares = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        panel_informacion1 = new javax.swing.JTextPane();
        boton_ruta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mapa");
        setBackground(new java.awt.Color(150, 152, 154));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("map.png"))); // NOI18N
        jButton4.setText("jButton4");

        boton_partida.setText("Seleccionar");
        boton_partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_partidaActionPerformed(evt);
            }
        });

        boton_destino.setText("Seleccionar ");
        boton_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_destinoActionPerformed(evt);
            }
        });

        boton_informacion.setText("Seleccionar");
        boton_informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_informacionActionPerformed(evt);
            }
        });

        puntos_salida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alajuela", "Alajuelita", "Belen", "Coronado", "Curridabat", "Desamparados", "Escazu", "Heredia", "Moravia", "Pavas", "Pozos", "Sabana", "San Pedro", "Santa Ana", "Zapote" }));

        puntos_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alajuela", "Alajuelita", "Belen", "Coronado", "Curridabat", "Desamparados", "Escazu", "Heredia", "Moravia", "Pavas", "Pozos", "Sabana", "San Pedro", "Santa Ana", "Zapote" }));

        jScrollPane3.setViewportView(panel_ruta);

        info_lugares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alajuela", "Alajuelita", "Belen", "Coronado", "Curridabat", "Desamparados", "Escazu", "Heredia", "Moravia", "Pavas", "Pozos", "Sabana", "San Pedro", "Santa Ana", "Zapote" }));

        jScrollPane4.setViewportView(panel_informacion1);

        boton_ruta.setText("Obtener");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puntos_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(boton_partida, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puntos_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addGap(106, 106, 106)
                        .addComponent(boton_ruta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info_lugares, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(2158, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1350, 1350, 1350)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(2290, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_destino)
                            .addComponent(boton_partida))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(puntos_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puntos_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(boton_informacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(info_lugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(boton_ruta)))))
                .addContainerGap(1166, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(482, 482, 482)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1241, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents





    private void boton_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_destinoActionPerformed
        // TODO add your handling code here:

        String destino = (String) puntos_destino.getSelectedItem();
        System.out.println(destino);
        set_get.getInstance().setPuntos_destino(destino);


    }//GEN-LAST:event_boton_destinoActionPerformed

    private void boton_partidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_partidaActionPerformed
        // TODO add your handling code here:

        String salida = (String) puntos_salida.getSelectedItem();
        System.out.println(salida);
        set_get.getInstance().setPuntos_salida(salida);



    }//GEN-LAST:event_boton_partidaActionPerformed

    private void boton_informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_informacionActionPerformed
        // TODO add your handling code here:
        
        //Obtener informacion de un Jcombobox
        String info_Lugar = (String) info_lugares.getSelectedItem();
        System.out.println(info_Lugar);
        set_get.getInstance().setInfo_lugares(info_Lugar);

        if (info_Lugar == "Alajuela"){
            panel_informacion1.setText("Habitantes:900´000 aprox\n\nDestacado: Mercado Municipal de Alajuela\n\nParque: Parque Juan Santamaría" +
                            "\n\nMonumentos: Monumento Próspero Fernández\n\nMuseo: Museo Histórico Cultural Juan Santamaría\n\nLugar de comida más popular: " +
                    "El Dorado\n\nGasolineras: Cootaxa");

        }
        else if (info_Lugar == "Alajuelita"){
            panel_informacion1.setText("Número de habitantes: 82´00 aprox\n\nParques: Parque Recreativo la Guaria\n\nMonumentos: Virgen inmaculada\n\n" +
                    "Museos: Castro Art Gallery\n\nLugares de comida más importantes: Fogo Rodizio\n\nGasolineras: Servicentro JSM Alajuelita");
        }
        else if (info_Lugar == "Belen"){
            panel_informacion1.setText("Número de habitantes: 23´000 aprox\n\nLugar destacado: Cariari Country Club\n\nParques: Parque Central Nicolás Ulloa" +
                    "Monumentos: Templo de San José\n\nMuseos: Museo Nacional\n\nLugares de comida más importantes: II Cavalino\n\nGasolineras: Servicentro Sheyza");
        }
        else if (info_Lugar == "Curridabat"){
            panel_informacion1.setText("Número de habitantes: 41´000 aprox\n\n" +
                    "Lugar destacado: Multiplaza del Este\n\n" +
                    "Parques: Parque del recuerdo\n\n" +
                    "Monumentos: Monumento en Parque de Curridabat\n\n" +
                    "Museos: Museo de la carreta\n\n" +
                    "Lugares de comida más importantes: Crepería Dulce Antojo\n\n" +
                    "Gasolineras: Gas LP EL Ranchito");
        }
        else if (info_Lugar == "Desamparados"){
            panel_informacion1.setText("Número de habitantes: 123´000 aprox\n\n" +
                    "Lugar destacado: Parque Acuático Cascada de Fuego\n\n" +
                    "Parques: Parque Centenario\n\n" +
                    "Monumentos: Mariposario Spirogyra\n\n " +
                    "Museos: Museo de la Carreta\n\n" +
                    "Lugares de comida más importantes: Soda Heidy y Yoguis\n\n " +
                    "Gasolineras: Metropoli gas LP Blueflame");
        }
        else if (info_Lugar == "Escazu"){
            panel_informacion1.setText("Número de habitantes: 15´000 aprox\n\n" +
                    "Lugar destacado: Multiplaza Escazú\n\n" +
                    "Parques: Parque Central de Escazú\n\n" +
                    "Monumentos: Monumento al Boyero\n\n" +
                    "Museos: Taller de Escultura IR\n\n" +
                    "Lugares de comida más importantes: La Posada de las Brujas\n\n" +
                    "Gasolineras: Gasolinera La Favorita");
        }
        else if (info_Lugar == "Moravia"){
            panel_informacion1.setText("Número de habitantes: 63´000 aprox\n\n" +
                    "Lugar destacado: Lincoln Plaza\n\n" +
                    "Parques: Parque Central Abraham Lincoln\n\n" +
                    "Monumentos: Parque Ecológico Itarar\n\n" +
                    "Museos: Museo Indígena\n\n" +
                    "Lugares de comida más importantes: Pizzería El Cubano \n\n" +
                    "Gasolineras: Delta Moravia");
        }
        else if (info_Lugar == "Pavas"){
            panel_informacion1.setText("Número de habitantes: 75´000 aprox\n\nLugar destacado: Embajada de los Estados Unidos de América\n\n" +
                    "Parques: Parque Bellavista\n\nAeropuerto: Aeropuerto Internacional Tobías Bolaños Palma\n\nMuseos: Museo Judío\n\n" +
                    "Lugares de comida más importantes: Restaurante Furca\n\nGasolineras: Delta Rohrmoser");
        }
        else if (info_Lugar == "Pozos"){
            panel_informacion1.setText("Número de habitantes: 16´000 aprox\n\nLugares destacados: Centro de Conservación Santa Ana"+
                    "Parques: Parque Bosques de Santa Ana\n\nMonumentos: Refugio Animal de Costa Rica\n\nMuseos:Galeria de Antiguedades\n\n" +
                    "Lugares de comida más importantes: La Casona de Laly\n\nGasolineras: Servicentro Pozos");
        }
        else if (info_Lugar == "Sabana"){
            panel_informacion1.setText("Número de habitantes: 5’000\n\n" +
                    "Lugar destacado: Estadio Nacional de Costa Rica\n\n" +
                    "Parques: Parque La Sabana\n\n" +
                    "Monumentos: Estatua León Cortés\n\n" +
                    "Museos: Museo de Arte Costarricense\n\n" +
                    "Lugares de comida más importantes: Soda Tapia\n\n" +
                    "Gasolineras: Bomba La Salle");
        }
        else if (info_Lugar == "San Pedro"){
            panel_informacion1.setText("Número de habitantes: 26´000 aprox\n\nLugar destacado: Mall San Pedro, UCR\n\nParques: Parque John F. kennedy\n\n" +
                    "Monumentos: La Fuente de la Hispanidad\n\nMuseos: UCR Museo de Insectos\n\nLugares de comida más importantes: Café 80´s San Pedro\n\n" +
                    "Gasolineras: Bomba San Pedro");
        }
        else if (info_Lugar == "Santa Ana"){
            panel_informacion1.setText("Número de habitantes: 13´000 aprox\n\nLugar destacado: Santa Ana Town Center\n\nParques:" +
                    "Parque Recreativo y Deportivo de Santa Ana\n\nHotel destacado: Hilton Garden INN Santa Ana SJO\n\nLugares de comida más importantes: " +
                    "Restaurante El Jardín\n\nGasolineras: Servicentro JSM Santa Ana");
        }
        else if (info_Lugar == "Zapote"){
            panel_informacion1.setText("Número de habitantes: 20´000 aprox\n\n" +
                    "Lugar destacado: Parroquia Nuestra Señora de Ujarrás\n\n" +
                    "Parques: Parque Central de Zapote\n\n" +
                    "Monumentos: Rotonda de las Garantías Sociales\n\n" +
                    "Museos: Plaza de Toros Zapote\n\n" +
                    "Lugares de comida más importantes: Limongi´s Resto Bar\n\n" +
                    "Gasolineras: Bomba La Pista");
        }
        else if (info_Lugar == "Coronado"){
            panel_informacion1.setText("Número de habitantes: 36´000 aprox\n\n" +
                    "Lugar destacado: Delicias Solamavi (Las Peludas)\n\n" +
                    "Parques: Parque de Vázquez de Coronado\n\n" +
                    "Monumentos: Parroquia de San Isidro Labrador\n\n" +
                    "Museos: UCR Instituto Clodomiro Picado\n\n" +
                    "Lugares de comida más importantes: El molino Central\n\n" +
                    "Gasolineras: El trapiche");
        }
        else if (info_Lugar == "Heredia"){
            panel_informacion1.setText("Número de habitantes: 140´000 aprox\n\nLugar destacado: Palacio de los Deportes\n\nParques: Parque Alfredo González Flores\n\n" +
                    "Monumentos: Monumento Parque el Carmen\n\nMuseos: Centro de la Cultura Herediana Omar Dengo\n\nLugares de comida más importantes: " +
                    "Carl´s Jr.\n\nGasolineras: Servicentro Santa Lucía");
        }




    }//GEN-LAST:event_boton_informacionActionPerformed









    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_destino;
    private javax.swing.JButton boton_informacion;
    private javax.swing.JButton boton_partida;
    private javax.swing.JButton boton_ruta;
    private javax.swing.JComboBox<String> info_lugares;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane panel_informacion1;
    private javax.swing.JTextPane panel_ruta;
    private javax.swing.JComboBox<String> puntos_destino;
    private javax.swing.JComboBox<String> puntos_salida;
    // End of variables declaration//GEN-END:variables
}
